/*
 * STEPPER_MOTOR_private.h
 *
 *  Created on: Sep 20, 2022
 *      Author: DELL
 */

#ifndef HAL_STEPPER_MOTOR_STEPPER_MOTOR_PRIVATE_H_
#define HAL_STEPPER_MOTOR_STEPPER_MOTOR_PRIVATE_H_



#endif /* HAL_STEPPER_MOTOR_STEPPER_MOTOR_PRIVATE_H_ */
